name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Deploy to App Engine
      uses: google-github-actions/deploy-appengine@v0.3.0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_email: ${{ secrets.GCP_SA_EMAIL }}
        credentials: ${{ secrets.GCP_SA_KEY }}
        promote: true
        stop_previous_version: true
        version: "production-${{ github.sha }}"
        args: "-q app.yaml"